### PR TITLE
Fix err for non-default workspace with empty state

### LINKED ISSUE #83: Improve user error when statefile is wiped on Consul restart
Users who are doing local development and testing with NIA may connect to a local Consul server, running some variant of:

```
$ consul agent -dev
```

when you restart the server, the KV is not persisted and erased. KV is where the Consul NIA stores the TF statefiles for tasks, resulting in task execution errors regarding workspace (visible when setting `driver.terraform.log=true` in the NIA config). The workspace is created by the TF client and is persisted on disk in the `nia-tasks` directory for each task.

```
2020/09/25 18:48:24.213053 [INFO] running Terraform command: PATH/terraform init -no-color -force-copy -input=false -lock-timeout=0s -backend=true -get=true -get-plugins=true -lock=true -upgrade=false -verify-plugins=true
Initializing modules...

Initializing the backend...

The currently selected workspace (print) does not exist.
  This is expected behavior when the selected workspace did not have an
  existing non-empty state. Please enter a number to select a workspace:
  
  1. default

  Enter a value: 

Error: Failed to select workspace: input not a valid number
```

I ran into this often with my local setup and would be useful to improve the error surfaced to end users to help understand and take action on.

### PR DESCRIPTION
**Pull request by findkim**
Executing terraform init for a non-default workspace that has an empty state causes an error. This adds edge case handling of the Terraform error to init, check the error, create workspace (which also sets up the backend), and init again.

This error is commonly ran into when using the default CTS option for Terraform state store, Consul KV. During development, the Consul server may be restarted and wiping the in-memory Consul KV along with the Terraform state files for CTS tasks. This also happens for other backends, in addition to Consul KV, when an existing task's state has been deleted because `.terraform/environment` manifest file with the workspace name is written to disk and subsequent inits have context of that workspace but not its state.

I chose to leave the `.terraform/environment` file as-is, and not editing or deleting it, to possibly preserve any other workspaces for the working directory CTS may not be aware of.

Resolves #83 #134

### CODE REVIEW

**Comment by findkim** [comment]
Ah hold on, this now breaks the happy path. Let me tinker a bit more before review

**Comment by findkim** [comment]
The initial approach was to select the default workspace first, then attempt init. However init would error on a new working directory.

I changed the approach on handling this edge case to follow the logic:
1. init
1. check error
1. create workspace -- this sets up the local manifest `.terraform/environment` as well as the backend if necessary. For Consul KV this step is needed. 
1. init again to setup module and providers.

File: client/terraform_cli_test.go [hunk 1]
```diff
@@ -148,8 +148,42 @@ func TestTerraformCLIInit(t *testing.T) {
 			}
 
 			assert.NoError(t, err)
+			m.AssertExpectations(t)
```
Comment (lornasong) [inline client/terraform_cli_test.go:151]: Oooo I've never used before ✨

**Review by lornasong — APPROVED** [review]
Cool. The tf flow looks tricky. Thanks for figuring this out!

File: client/terraform_cli.go [hunk 2]
```diff
@@ -85,20 +90,42 @@ func NewTerraformCLI(config *TerraformCLIConfig) (*TerraformCLI, error) {
 // Init initializes by executing the cli command `terraform init` and
 // `terraform workspace new <name>`
 func (t *TerraformCLI) Init(ctx context.Context) error {
+	var wsCreated bool
+
+	// This is special handling for when the workspace has been detected in
+	// .terraform/environment without a non-empty state. This case is common
+	// when the state for the workspace has been deleted.
+TF_INIT_AGAIN:
```
Comment (eikenb) [inline client/terraform_cli.go:98]: Normally I prefer explicit loops instead of goto's but this does read pretty well. Conveys (better than a loop would) that this should work the first time, except for this one situation where we need to try again.

File: client/terraform_cli_test.go [hunk 3]
```diff
@@ -148,8 +148,42 @@ func TestTerraformCLIInit(t *testing.T) {
...
 		})
 	}
+
+	t.Run("workspace artifact with empty state", func(t *testing.T) {
+		// Edge case to handle https://github.com/hashicorp/terraform/issues/21393
+		initErr := errors.New(`Initializing the backend...
```
Comment (eikenb) [inline client/terraform_cli_test.go:157]: Does tfexec/terraform fall back into an interactive mode here? That seems.. strange.

**Review by eikenb — APPROVED** [review]

File: client/terraform_cli_test.go (hunk 3 above)
Comment (findkim) [reply client/terraform_cli_test.go:157]: Yeah it's a Terraform bug where it errors with an interactive message but TF is ran in automation with tfexec which disables input.

Comment (findkim) [reply client/terraform_cli_test.go:157]: That being said, i'll include the GH issue where the logic is above in addition to this test case to keep context collocated

File: client/terraform_cli.go (hunk 2 above)
Comment (findkim) [reply client/terraform_cli.go:98]: 👍 I rarely use goto loops but it felt even worse writing the nesting with 1 retry logic.
